version: '3.8'

services:
  web:
    build: .
#    command: python /book/manage.py runserver 0.0.0.0:8000
    command: gunicorn config.wsgi -b 0.0.0.:8000
    volumes:
      - .:/book
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - 'DJANGO_SECRET_KEY=django-insecure-n%%_qg)b-43qgu0$n+_g&ozvmaaff#o+yn-4b&-bteetg+!n-%'
      - 'DJANGO_DEBUG=True'
      - 'DJANGO_SECURE_HSTS_SECONDS=0'
      - 'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False'
      - 'DJANGO_SECURE_HSTS_PRELOAD=False'
      - 'DJANGO_SESSION_COOKIE_SECURE=False'
      - 'DJANGO_CSRF_COOKIE_SECURE=False'
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: