version: '3.8'

services:
  web:
    build: .
    command: python /book/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/book
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - 'DJANGO_SECRET_KEY=django-insecure-n%%_qg)b-43qgu0$n+_g&ozvmaaff#o+yn-4b&-bteetg+!n-%'
      - 'DJANGO_DEBUG=True'
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: