version: '3.8'

services:
  web:
    build: .
    command: python /book/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/book
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - 'DJANGO_SECRET_KEY=I5ixvmCTs5kfOUpx1Hy35qCDPxwq11jXB7X02DcIhUTDLi151AM'
      - 'DJANGO_SECURE_SSL_REDIRECT=False'
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: