# Generated by Django 3.1.14 on 2023-10-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_method', 'Can read all books')]},
        ),
    ]
